# Generated by Django 5.0.6 on 2024-05-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", models.CharField(max_length=11, unique=True)),
                ("nome", models.CharField(max_length=70)),
                ("data_nascimento", models.DateField()),
            ],
        ),
    ]
